// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCW6dqrcmz_rewvam0MX-Yt9ki05wD-GVE',
//     appId: '1:917815266045:web:6e2deb4e2a90a42aa80c94',
//     messagingSenderId: '917815266045',
//     projectId: 'savewiser-becae',
//     authDomain: 'savewiser-becae.firebaseapp.com',
//     storageBucket: 'savewiser-becae.firebasestorage.app',
//     measurementId: 'G-9Q6SV4GDJ2',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDmpBnWlQVJszbXxRwEjnjfaWB6_FBIwlk',
//     appId: '1:917815266045:android:7da1eb8b2129564ca80c94',
//     messagingSenderId: '917815266045',
//     projectId: 'savewiser-becae',
//     storageBucket: 'savewiser-becae.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDGr0gJo7xBHRjfoCnnm4gErsSft_ECgN4',
//     appId: '1:917815266045:ios:0812b1949d411e0ca80c94',
//     messagingSenderId: '917815266045',
//     projectId: 'savewiser-becae',
//     storageBucket: 'savewiser-becae.firebasestorage.app',
//     iosBundleId: 'com.example.savewiser',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDGr0gJo7xBHRjfoCnnm4gErsSft_ECgN4',
//     appId: '1:917815266045:ios:0812b1949d411e0ca80c94',
//     messagingSenderId: '917815266045',
//     projectId: 'savewiser-becae',
//     storageBucket: 'savewiser-becae.firebasestorage.app',
//     iosBundleId: 'com.example.savewiser',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCW6dqrcmz_rewvam0MX-Yt9ki05wD-GVE',
//     appId: '1:917815266045:web:980264f33c51d36da80c94',
//     messagingSenderId: '917815266045',
//     projectId: 'savewiser-becae',
//     authDomain: 'savewiser-becae.firebaseapp.com',
//     storageBucket: 'savewiser-becae.firebasestorage.app',
//     measurementId: 'G-N56EM4S2WJ',
//   );
// }
