import 'package:hive/hive.dart';

part 'transaction.g.dart'; // Will be generated by build_runner

@HiveType(typeId: 0)
class Transaction extends HiveObject {
  @HiveField(0)
  String category; // Needs, Wants, Savings

  @HiveField(1)
  double amount;

  @HiveField(2)
  int month;

  @HiveField(3)
  int year;

  Transaction({
    required this.category,
    required this.amount,
    required this.month,
    required this.year,
  });
}
